telegram:
  bot:
    enabled: ${TELEGRAM_BOT_ENABLED:true}

spring:
  application:
    name: telegram-channel

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: telegram-channel-consumer-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONNECT_STRING:localhost:2181}

logging:
  level:
    org.apache.kafka: WARN
    io.omnika.common.ipc: DEBUG
