project:
  title: Omnika Management Service

server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: management-service

  datasource:
#    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/omnika_management_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_MODE:update}
  flyway:
    enabled: false
    locations: classpath:db/migration/common

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: management-service-consumer-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONNECT_STRING:localhost:2181}

security:
  token:
    signing_key: ${SECURITY_TOKEN_SIGNING_KEY:abababa}
    lifetime: ${SECURITY_TOKEN_LIFETIME:86400}  # 24 hours by default
    request_header: ${SECURITY_TOKEN_REQUEST_HEADER:X-Authorization}