version: '2.2'

services:
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper
    restart: always
    ports:
      - '2181:2181'
      - '12181:12181'

  rabbitmq:
    image: rabbitmq:3.8.27-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'